DROP TABLE IF EXISTS Vehicles CASCADE;
DROP TABLE IF EXISTS ParkingSlots CASCADE;
DROP TABLE IF EXISTS ParkingLots CASCADE;
DROP TABLE IF EXISTS ParkingSessions CASCADE;
DROP TABLE IF EXISTS Maintenance CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TYPE IF EXISTS user_role;